# Practical 1

# Demontrate array and matrix manipulation using Numpy library

In [1]:
import numpy as np  #importing numpy dictionary as np.

In [2]:
print (np.__version__)  #we are using this command to check the version of Anaconda.

1.21.5


In [3]:
ar1 = np.array(5)  #this command is used to create an array. This is an array of '0' dimension. It is called 0-D Array

In [4]:
print (ar1)  #print the array.

5


In [5]:
print(type(ar1))  #this is used to print the type of object.

<class 'numpy.ndarray'>


In [6]:
print(ar1.dtype)  #this is used to print the type of layout of array.

int32


In [7]:
ar2=np.array([1,2,3,4,5,6,7,8])  #create another array.

In [8]:
np.size(ar2)  #check the size of of array i.e. number of elements.

8

In [9]:
print(ar2)  #obtain the output.

[1 2 3 4 5 6 7 8]


In [10]:
print (ar2[3:5])  #obtain output bt slicing.

[4 5]


In [11]:
print(type(ar2))  #this is used to print the type of object.

<class 'numpy.ndarray'>


In [12]:
print(type(ar2[0]))  #this is used to print the type of particular item from the array.

<class 'numpy.int32'>


In [13]:
print(ar2.dtype)  #this is used to print the type of layout of array.

int32


In [14]:
ar3=np.array([3.1,3.2,3.3,3.4,3.5,3.6,3.7])  #creating an 1-D Array

In [15]:
print(ar3)  #printing the array

[3.1 3.2 3.3 3.4 3.5 3.6 3.7]


In [16]:
np.size(ar3)  #gives the size of array i.e. no of elements

7

In [17]:
print(type(ar3))  #this is used to print the type of object.

<class 'numpy.ndarray'>


In [18]:
print(ar3.dtype)  #this is used to print the type of layout of array.

float64


In [19]:
print(type(ar3[0]))  #this is used to print the type of object.

<class 'numpy.float64'>


In [20]:
ar4=np.array(["aniket","anshul"])  #creating an array whiich include strings

In [21]:
print(type(ar4))  #this is used to print the type of object.

<class 'numpy.ndarray'>


In [22]:
print(type(ar4[0]))  #this is used to print the type of element in object.

<class 'numpy.str_'>


In [23]:
print(ar4.dtype)  #this is used to print the type of layout of array.

<U6


In [24]:
np.size(ar4)  #check the size of of array i.e. number of elements.

2

In [25]:
ar5=np.array([[1,2,3],[4,5,6],[7,8,9]])  #creating a 2-D Array

In [26]:
print(ar4)  #printing the array

['aniket' 'anshul']


In [27]:
print(type(ar5))  #this is used to print the type of object.

<class 'numpy.ndarray'>


In [28]:
print(ar5[1,2])  #printing the element of array using indexing

6


In [29]:
np.size(ar5)  #check the size of of array i.e. number of elements.

9

In [30]:
print(ar5[2,2])  #printing the element of array using indexing

9


In [31]:
print(ar5.dtype)  #this is used to print the type of layout of array.

int32


In [32]:
ar1.shape  #get no. of rows and columns of the array.

()

In [33]:
ar2.shape  #get no. of rows and columns of the array.

(8,)

In [34]:
ar3.shape  #get no. of rows and columns of the array.

(7,)

In [35]:
ar4.shape  #get no. of rows and columns of the array.

(2,)

In [36]:
ar5.shape  #get no. of rows and columns of the array.

(3, 3)

In [37]:
ar6=np.array([[1,2,],[3,4,5],[6,7,8,9]])

C:\Users\ANIKET KUMAR\AppData\Local\Temp\ipykernel_18032\3224027040.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar6=np.array([[1,2,],[3,4,5],[6,7,8,9]])


In [38]:
print(ar6)  #printing the array

[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]


In [39]:
print(type(ar6))  #this is used to print the type of object.

<class 'numpy.ndarray'>


In [40]:
print(type(ar6[0]))  #this is used to print the type of element in object.

<class 'list'>


In [41]:
ar6.dtype  #this is used to print the type of layout of array.

dtype('O')

In [42]:
np.size(ar6)  #check the size of of array i.e. number of elements.

3

In [43]:
ar6.shape  #get no. of rows and columns of the array.

(3,)

In [44]:
ar7=np.array([[1,2,],"aniket",[6,7,8,9]])

C:\Users\ANIKET KUMAR\AppData\Local\Temp\ipykernel_18032\1336259499.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar7=np.array([[1,2,],"aniket",[6,7,8,9]])


In [45]:
print(ar7)  #printing the array

[list([1, 2]) 'aniket' list([6, 7, 8, 9])]


In [46]:
ar8=np.array([[[1,2,],[3,4,5],[6,7,8,9]],[[1,3],[2,4,5],[4,5,6,7]],[[2,3],[4,5,6],[4,5,6,7]]])

C:\Users\ANIKET KUMAR\AppData\Local\Temp\ipykernel_18032\2423923415.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  ar8=np.array([[[1,2,],[3,4,5],[6,7,8,9]],[[1,3],[2,4,5],[4,5,6,7]],[[2,3],[4,5,6],[4,5,6,7]]])


In [47]:
print(ar8)  #printing the array

[[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]
 [list([1, 3]) list([2, 4, 5]) list([4, 5, 6, 7])]
 [list([2, 3]) list([4, 5, 6]) list([4, 5, 6, 7])]]


In [48]:
ar9=np.array([[[1,2,],[3,4],[6,7]],[[1,3],[2,4],[4,5]],[[2,3],[4,5],[4,5]]])

In [49]:
print(ar9)  #printing the array

[[[1 2]
  [3 4]
  [6 7]]

 [[1 3]
  [2 4]
  [4 5]]

 [[2 3]
  [4 5]
  [4 5]]]


In [50]:
ar9.dtype  #this is used to print the type of layout of array.

dtype('int32')

In [51]:
ar9.shape  #get no. of rows and columns of the array.

(3, 3, 2)

In [52]:
print(type(ar9))  #this is used to print the type of object.

<class 'numpy.ndarray'>


In [53]:
print(type(ar9[0]))  #this is used to print the type of element in object.

<class 'numpy.ndarray'>


In [54]:
import numpy as np  #importing numpy dictionary as np.

In [55]:
arr2= np.array([[1,2,3,4],[5,6,7,8]])  #creating 2-D Array

In [56]:
print(arr2[0,3])  #retrieving single element using indexing

4


In [57]:
print(arr2[1,3])  #retrieving single element using indexing

8


In [58]:
arr3= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])  #creating 3-D Array

In [59]:
print(arr3[1,1,0])  #retrieving single element using indexing

10


In [60]:
print(arr3[0,1,1])  #retrieving single element using indexing

5


In [61]:
arr2= np.array([[1,2,3,4],[5,6,7,8]])  #creating 2-D array

In [62]:
print(arr2[1,-1])    #retrieving single element using negative indexing

8


In [63]:
arr = np.array([1,2,3,4,5,6,7])  #creating 1-D array

In [64]:
print(arr[1 : 5])  #using slicing to print array

[2 3 4 5]


In [65]:
print(arr[2:])  #using slicing to print array

[3 4 5 6 7]


In [66]:
print(arr[4 : 6])  #using slicing to print array

[5 6]


In [67]:
print(arr[-3:-1])  #using negative slicing to print array

[5 6]


In [68]:
print(arr[::-1])  #using slicing to print array

[7 6 5 4 3 2 1]


In [69]:
print(arr[::2])  #using slicing to print array

[1 3 5 7]


In [70]:
print(arr[1::2])  #using slicing to print array

[2 4 6]


In [71]:
arr1= (np.arange(1,50,2,float))  #Creates an array by using the evenly spaced values over the given interval range.

In [72]:
print(arr1)

[ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19. 21. 23. 25. 27. 29. 31. 33. 35.
 37. 39. 41. 43. 45. 47. 49.]


In [73]:
arr4= (np.arange(10,100.5,3.3,float))  #Creates an array by using the evenly spaced values over the given interval range.

In [74]:
print(arr4)  #printing the array

[10.  13.3 16.6 19.9 23.2 26.5 29.8 33.1 36.4 39.7 43.  46.3 49.6 52.9
 56.2 59.5 62.8 66.1 69.4 72.7 76.  79.3 82.6 85.9 89.2 92.5 95.8 99.1]


In [75]:
arr5 = np.linspace(1,20,10)  #returns the evenly spaced values over the given interval.

In [76]:
print(arr5)  #printing the array

[ 1.          3.11111111  5.22222222  7.33333333  9.44444444 11.55555556
 13.66666667 15.77777778 17.88888889 20.        ]


In [77]:
arr6 = np.array([[1,12,3],[4,5,3]])  #creating 2-D Array

In [78]:
print(arr6.max(axis = 0)) #to find maximum element of the column elements

[ 4 12  3]


In [79]:
print(arr6.max(axis = 1))  #to find maximum element of the row elements

[12  5]


In [80]:
print(arr6.min(axis = 0))  #to find minimum element of the column elements

[1 5 3]


In [81]:
print(arr6.min(axis = 1))  #to find maximum element of the row elements

[1 3]


In [82]:
print(arr6.sum(axis = 0))  #to find the sum of all elements of the column

[ 5 17  6]


In [83]:
print(arr6.min(axis = 1))  #to find the sum of all elements of the row

[1 3]


In [84]:
print(arr6.max())  #gives the maximum value in the array

12


In [85]:
print(arr6.min())  #gives the minimum value in the array

1


In [86]:
print(arr6.sum())  #gives the sum of all elements of value in the array

28


In [87]:
arr7 = np.array([[7,16,3],[9,7,9]])  #creating 2-D Array

In [88]:
print(np.sqrt(arr7))  #return the square root og the elements of array

[[2.64575131 4.         1.73205081]
 [3.         2.64575131 3.        ]]


In [89]:
arr8=np.array([[4,8,6],[8,9,6]])
arr9=np.array([[76,9,4],[9,6,8]])


In [90]:
print(arr8+arr9)  #gives the sum of two array

[[80 17 10]
 [17 15 14]]


In [91]:
print(arr8*arr9)  #gives the profuct of two array

[[304  72  24]
 [ 72  54  48]]


In [92]:
print(np.mean(arr8))  #gives the mean value of elements of array

6.833333333333333


In [93]:
print(np.mean(arr8,axis= 0))  #gives the mean value of elements of array column vise

[6.  8.5 6. ]


In [94]:
print(np.mean(arr8,axis= 1))  #gives the mean value of elements of array row vise

[6.         7.66666667]


In [95]:
arr10 = np.empty((9,9), dtype= int, order='c')
print(arr10)  #This method creates an empty or uninitialized array of 9*9 which is row-major

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [96]:
arr10 = np.empty((9,9), dtype= int, order='f')
print(arr10)  #This method creates an empty or uninitialized array of 9*9 which is column-major

[[        -1          0          0          0 -640882144          0
          15          0          0]
 [        -1 -502068752          0          7        469          0
           0          1          0]
 [        -1      32762          0          0          3          0
  -638315776          0          0]
 [        -1         -1          0          1          1 -638316032
         469          0          0]
 [        -1          0        257          0 -709944272        469
  -502555059          0          0]
 [        -1 -502068312       1000          0        469          0
       32762          0          0]
 [-502068424      32762        500          0          5          0
           0          0          0]
 [     32762          2         -1 -638216160          0          0
           0          0          0]
 [         0          0         -1        469          1          0
          15          0          0]]


In [97]:
arr10 = np.zeros((9,9), dtype= int, order='f')
print(arr10)  #Creates numpy array of 9*9 with each array element is initialized to 0

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


In [98]:
arr11 = np.ones((9,9), dtype= int, order='f')
print(arr11)  # Creates numpy array of 9*9 with each array element is initialized to 1

[[1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1]]


In [99]:
arr12= np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr12:
    print(i)  #iteration in 1-D Array

1
2
3
4
5
6
7
8
9
10


In [100]:
arr13= np.array([[1,2,3],[4,5,6],[7,8,9]])
count : int=0
for row in arr13:  #for loop to print each row of 2-D array
    count = count+1
    print("row",count," : ", row)

row 1  :  [1 2 3]
row 2  :  [4 5 6]
row 3  :  [7 8 9]


In [101]:
for row in arr13:
    for i in row:
        print(i)  #for loops to print each scalar or individual elements

1
2
3
4
5
6
7
8
9


In [102]:
arr14=np.array([[[1,2,],[3,4,5],[6,7,8,9]],[[1,3],[2,4,5],[4,5,6,7]],[[2,3],[4,5,6],[4,5,6,7]]])
print(arr14)

[[list([1, 2]) list([3, 4, 5]) list([6, 7, 8, 9])]
 [list([1, 3]) list([2, 4, 5]) list([4, 5, 6, 7])]
 [list([2, 3]) list([4, 5, 6]) list([4, 5, 6, 7])]]


C:\Users\ANIKET KUMAR\AppData\Local\Temp\ipykernel_18032\4014758674.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr14=np.array([[[1,2,],[3,4,5],[6,7,8,9]],[[1,3],[2,4,5],[4,5,6,7]],[[2,3],[4,5,6],[4,5,6,7]]])


In [103]:
import numpy
import numpy.matlib as nm
print(nm.empty((3,4)))  #It is used to return a matrix with the uninitialized entries


[[9.97022310e-312 2.81617418e-322 0.00000000e+000 0.00000000e+000]
 [1.20953760e-312 3.69776220e-062 4.51136903e-090 1.08533659e-042]
 [1.52451998e-052 1.10633317e+165 6.48224659e+170 4.93432906e+257]]


In [104]:
print(nm.zeros((3,3)))  # Creates a matrix where the entries are initialized to zero

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [105]:
print(nm.ones((3,3)))  # Creates a matrix where the entries are initialized to one

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
